sudo: required

language: python

python:
 - 2.7
 - 3.5

env:
  matrix:
  - DJANGO_VERSION=1.11.*
  - DJANGO_VERSION=2.0.*
  - DJANGO_VERSION=2.1.*

matrix:
 exclude:
  - python: 2.7
    env: DJANGO_VERSION=2.0.*
  - python: 2.7
    env: DJANGO_VERSION=2.1.*

install:
 - pip install -r requirements.txt
 - pip install coverage
 - pip install flake8
 - pip install -U django==$DJANGO_VERSION

before_script:
 - flake8 paperclip

script:
 - coverage run manage.py test

after_success:
 - pip install coveralls
 - coveralls
