sudo: required

language: python

python:
 - 3.4
 - 3.5
 - 3.6
 - 3.7
 - 3.8

env:
  matrix:
  - DJANGO_VERSION=2.2.*
  - DJANGO_VERSION=3.0.*

matrix:
  exclude:
   - python: 3.4
     env: DJANGO_VERSION=2.2.*
   - python: 3.4
     env: DJANGO_VERSION=3.0.*
   - python: 3.5
     env: DJANGO_VERSION=3.0.*


install:
 - pip install -r requirements.txt
 - pip install coverage
 - pip install flake8
 - pip install django==$DJANGO_VERSION -U

before_script:
 - flake8 paperclip

script:
 - coverage run manage.py test

after_success:
 - pip install coveralls
 - coveralls
